package com.keetr.snac.core.network.movie.fake

val MovieDetailsResponse = """{
  "adult": false,
  "backdrop_path": "/fhquRW28vRZHr26orSaFFnhYIA0.jpg",
  "belongs_to_collection": {
    "id": 735127,
    "name": "Extraction Collection",
    "poster_path": "/r3UzhVpENoCb8n2bZPClWdhsSH8.jpg",
    "backdrop_path": "/gxBbFVb2SUWtHTJQXjwAtEPTWcA.jpg"
  },
  "budget": 0,
  "genres": [
    {
      "id": 28,
      "name": "Action"
    },
    {
      "id": 53,
      "name": "Thriller"
    }
  ],
  "homepage": "https://www.netflix.com/title/81098494",
  "id": 697843,
  "imdb_id": "tt12263384",
  "original_language": "en",
  "original_title": "Extraction 2",
  "overview": "Tasked with extracting a family who is at the mercy of a Georgian gangster, Tyler Rake infiltrates one of the world's deadliest prisons in order to save them. But when the extraction gets hot, and the gangster dies in the heat of battle, his equally ruthless brother tracks down Rake and his team to Vienna, in order to get revenge.",
  "popularity": 2257.02,
  "poster_path": "/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg",
  "production_companies": [
    {
      "id": 106544,
      "logo_path": "/psd84iF7PTGrKf4yFOStKj8JbAh.png",
      "name": "AGBO",
      "origin_country": "US"
    },
    {
      "id": 104576,
      "logo_path": "/sNhEzePPkxW3AKqr3l0h7I1k0hR.png",
      "name": "Filmhaus Films",
      "origin_country": "AT"
    }
  ],
  "production_countries": [
    {
      "iso_3166_1": "AT",
      "name": "Austria"
    },
    {
      "iso_3166_1": "US",
      "name": "United States of America"
    }
  ],
  "release_date": "2023-06-09",
  "revenue": 0,
  "runtime": 123,
  "spoken_languages": [
    {
      "english_name": "English",
      "iso_639_1": "en",
      "name": "English"
    },
    {
      "english_name": "Georgian",
      "iso_639_1": "ka",
      "name": "ქართული"
    }
  ],
  "status": "Released",
  "tagline": "Prepare for the ride of your life.",
  "title": "Extraction 2",
  "video": false,
  "vote_average": 7.625,
  "vote_count": 1097,
  "credits": {
    "cast": [
      {
        "adult": false,
        "gender": 2,
        "id": 74568,
        "known_for_department": "Acting",
        "name": "Chris Hemsworth",
        "original_name": "Chris Hemsworth",
        "popularity": 82.305,
        "profile_path": "/jpurJ9jAcLCYjgHHfYF32m3zJYm.jpg",
        "cast_id": 4,
        "character": "Tyler Rake",
        "credit_id": "6007d3f80816c7003ef86bf5",
        "order": 0
      },
      {
        "adult": false,
        "gender": 1,
        "id": 229932,
        "known_for_department": "Acting",
        "name": "Golshifteh Farahani",
        "original_name": "Golshifteh Farahani",
        "popularity": 129.952,
        "profile_path": "/lbsd2lAIQq4egOUXDIfjhte12vv.jpg",
        "cast_id": 7,
        "character": "Nik Khan",
        "credit_id": "617d2002be2d4900666ddac9",
        "order": 1
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1886169,
        "known_for_department": "Acting",
        "name": "Adam Bessa",
        "original_name": "Adam Bessa",
        "popularity": 17.42,
        "profile_path": "/nk0YOk4cdl9w9C1bVEbhj1U287L.jpg",
        "cast_id": 8,
        "character": "Yaz Khan",
        "credit_id": "629f0e2412197e1689f50145",
        "order": 2
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1106890,
        "known_for_department": "Acting",
        "name": "Tornike Gogrichiani",
        "original_name": "Tornike Gogrichiani",
        "popularity": 55.823,
        "profile_path": "/rUEoEqVC5EFNgOGyYPWSTdwvwu.jpg",
        "cast_id": 44,
        "character": "Zurab Radiani / Nikoloz Radiani",
        "credit_id": "648be5d5076ce800e743404e",
        "order": 3
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1150149,
        "known_for_department": "Acting",
        "name": "Tornike Bziava",
        "original_name": "Tornike Bziava",
        "popularity": 4.325,
        "profile_path": "/brZSTPCKTfDOCcc7ZsqHbsENpZy.jpg",
        "cast_id": 12,
        "character": "David Radiani",
        "credit_id": "629f0e797d5db508699b2f4e",
        "order": 4
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1122543,
        "known_for_department": "Acting",
        "name": "Tinatin Dalakishvili",
        "original_name": "Tinatin Dalakishvili",
        "popularity": 56.396,
        "profile_path": "/ulnFxigewurjUXWEZLLgva47XH8.jpg",
        "cast_id": 10,
        "character": "Ketevan Radiani",
        "credit_id": "629f0e45c8a2d4005047a6d1",
        "order": 5
      },
      {
        "adult": false,
        "gender": 2,
        "id": 4114633,
        "known_for_department": "Acting",
        "name": "Andro Japaridze",
        "original_name": "Andro Japaridze",
        "popularity": 16.071,
        "profile_path": "/nz8kZo5jS5cUcazNxYeCDTuo6s6.jpg",
        "cast_id": 40,
        "character": "Sandro Radiani",
        "credit_id": "648be58cc3c89100cad9395c",
        "order": 6
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1849385,
        "known_for_department": "Crew",
        "name": "Justin Howell",
        "original_name": "Justin Howell",
        "popularity": 3.159,
        "profile_path": "/fMo49t3T3AUaUDUAQqJqFbX1DOQ.jpg",
        "cast_id": 9,
        "character": "Gio",
        "credit_id": "629f0e3853866e00519449d5",
        "order": 7
      },
      {
        "adult": false,
        "gender": 2,
        "id": 17605,
        "known_for_department": "Acting",
        "name": "Idris Elba",
        "original_name": "Idris Elba",
        "popularity": 44.485,
        "profile_path": "/be1bVF7qGX91a6c5WeRPs5pKXln.jpg",
        "cast_id": 39,
        "character": "Alcott",
        "credit_id": "648be564559d2200ad812225",
        "order": 8
      },
      {
        "adult": false,
        "gender": 1,
        "id": 18182,
        "known_for_department": "Acting",
        "name": "Olga Kurylenko",
        "original_name": "Olga Kurylenko",
        "popularity": 46.417,
        "profile_path": "/q0QXFRg5bSnaLjbvhamfclt0eId.jpg",
        "cast_id": 30,
        "character": "Mia",
        "credit_id": "642ffbf4e92d830077f7971e",
        "order": 9
      },
      {
        "adult": false,
        "gender": 1,
        "id": 2656292,
        "known_for_department": "Acting",
        "name": "Sinéad Phelps",
        "original_name": "Sinéad Phelps",
        "popularity": 10.685,
        "profile_path": "/oTARQq8oYMkaSqnTZJ8b6QsWO7A.jpg",
        "cast_id": 11,
        "character": "Kutaisi Staff",
        "credit_id": "629f0e53dc1cb452deccf9a7",
        "order": 10
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1193191,
        "known_for_department": "Production",
        "name": "Patrick Newall",
        "original_name": "Patrick Newall",
        "popularity": 2.475,
        "profile_path": "/dOGLRCvGb8mCXSjoDAq4l9Xroob.jpg",
        "cast_id": 13,
        "character": "Seb",
        "credit_id": "629f0e881130bd0066b168d0",
        "order": 11
      },
      {
        "adult": false,
        "gender": 2,
        "id": 9452,
        "known_for_department": "Acting",
        "name": "Daniel Bernhardt",
        "original_name": "Daniel Bernhardt",
        "popularity": 18.454,
        "profile_path": "/b59qhg5VJOCypx9eMXrXHAjauLd.jpg",
        "cast_id": 43,
        "character": "Konstantine",
        "credit_id": "648be5c7c3c89100ae4fdd15",
        "order": 12
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2809710,
        "known_for_department": "Acting",
        "name": "Levan Saginashvili",
        "original_name": "Levan Saginashvili",
        "popularity": 2.07,
        "profile_path": "/jXd70ZG93YSdNANGgr0S5ENMVRb.jpg",
        "cast_id": 45,
        "character": "Vakhtang",
        "credit_id": "648be5e4559d2200ad8122ae",
        "order": 13
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1599245,
        "known_for_department": "Acting",
        "name": "George Lasha",
        "original_name": "George Lasha",
        "popularity": 2.567,
        "profile_path": "/vIfBzNhjOrmvubovIutWibvhoRO.jpg",
        "cast_id": 46,
        "character": "Sergo",
        "credit_id": "648be5f5559d22011c4b1348",
        "order": 14
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1120883,
        "known_for_department": "Acting",
        "name": "Sam Hargrave",
        "original_name": "Sam Hargrave",
        "popularity": 28.611,
        "profile_path": "/mq7KgHiyuwFOvxuEg8p0Z30pybY.jpg",
        "cast_id": 102,
        "character": "Ditch Digger",
        "credit_id": "648f8b68c2ff3d011cba24a4",
        "order": 15
      },
      {
        "adult": false,
        "gender": 0,
        "id": 4114635,
        "known_for_department": "Acting",
        "name": "Miriam Kovziashvili",
        "original_name": "Miriam Kovziashvili",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 42,
        "character": "Nina Radiani",
        "credit_id": "648be5b1c3c891012d5c9557",
        "order": 16
      },
      {
        "adult": false,
        "gender": 0,
        "id": 4114634,
        "known_for_department": "Acting",
        "name": "Marta Kovziashvili",
        "original_name": "Marta Kovziashvili",
        "popularity": 0.836,
        "profile_path": null,
        "cast_id": 41,
        "character": "Nina Radiani",
        "credit_id": "648be5a0c2ff3d00c598e53a",
        "order": 17
      },
      {
        "adult": false,
        "gender": 0,
        "id": 4120711,
        "known_for_department": "Acting",
        "name": "Demetre Kavelashvili",
        "original_name": "Demetre Kavelashvili",
        "popularity": 1.4,
        "profile_path": null,
        "cast_id": 103,
        "character": "Zurab Radiani (12 years old)",
        "credit_id": "6490e9af976a23013b3f1276",
        "order": 18
      },
      {
        "adult": false,
        "gender": 0,
        "id": 4120712,
        "known_for_department": "Acting",
        "name": "Giga Shavadze",
        "original_name": "Giga Shavadze",
        "popularity": 1.62,
        "profile_path": null,
        "cast_id": 104,
        "character": "Davit Radiani (9 years old)",
        "credit_id": "6490e9b942bf010101bff0d8",
        "order": 19
      },
      {
        "adult": false,
        "gender": 2,
        "id": 18283,
        "known_for_department": "Acting",
        "name": "Dato Bakhtadze",
        "original_name": "Dato Bakhtadze",
        "popularity": 26.592,
        "profile_path": "/1iittoHHIZtIalNt3DYsDu86FwL.jpg",
        "cast_id": 105,
        "character": "Avtandil",
        "credit_id": "6490e9e0c2ff3d00e2e1b921",
        "order": 20
      },
      {
        "adult": false,
        "gender": 0,
        "id": 4120713,
        "known_for_department": "Acting",
        "name": "Davit Chogovadze",
        "original_name": "Davit Chogovadze",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 106,
        "character": "Avtandil (20 years old)",
        "credit_id": "6490e9f042bf01013bbe7ec1",
        "order": 21
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2037582,
        "known_for_department": "Acting",
        "name": "Irakli Kvirikadze",
        "original_name": "Irakli Kvirikadze",
        "popularity": 3.065,
        "profile_path": "/gAvIIxZugyLgJ6zK3D6H1QLBYGt.jpg",
        "cast_id": 107,
        "character": "Ivayne",
        "credit_id": "6490ea2442bf0100ae32d2e5",
        "order": 22
      },
      {
        "adult": false,
        "gender": 2,
        "id": 4120723,
        "known_for_department": "Acting",
        "name": "Paul Maynard",
        "original_name": "Paul Maynard",
        "popularity": 1.382,
        "profile_path": "/pAWkyROPHN1b8JLdAdYmGU0c9bR.jpg",
        "cast_id": 108,
        "character": "Merc Emergency Doctor",
        "credit_id": "6490eae2c2ff3d00e2e1b95a",
        "order": 23
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2614157,
        "known_for_department": "Acting",
        "name": "Héctor Andreu",
        "original_name": "Héctor Andreu",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 109,
        "character": "Petrusko",
        "credit_id": "6490f09e976a23011e1beae6",
        "order": 24
      },
      {
        "adult": false,
        "gender": 0,
        "id": 4120737,
        "known_for_department": "Acting",
        "name": "Tite Komakhidze",
        "original_name": "Tite Komakhidze",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 110,
        "character": "Portly Guard",
        "credit_id": "6490f0aac2ff3d00ffbcf22c",
        "order": 25
      }
    ],
    "crew": [
      {
        "adult": false,
        "gender": 2,
        "id": 950,
        "known_for_department": "Editing",
        "name": "Pietro Scalia",
        "original_name": "Pietro Scalia",
        "popularity": 4.544,
        "profile_path": "/cy4XviFjYDwyvfM4aqcxOV96MMq.jpg",
        "credit_id": "648d59a342bf0100ae30fcc6",
        "department": "Editing",
        "job": "Additional Editing"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1317,
        "known_for_department": "Art",
        "name": "Philip Ivey",
        "original_name": "Philip Ivey",
        "popularity": 1.673,
        "profile_path": null,
        "credit_id": "648c888ec3c891012d5cdbd0",
        "department": "Art",
        "job": "Production Design"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2122,
        "known_for_department": "Editing",
        "name": "William Hoy",
        "original_name": "William Hoy",
        "popularity": 2.571,
        "profile_path": "/5UoZPWvGDKzUvJfRFavwOYM8Enz.jpg",
        "credit_id": "648c8862c3c891012d5cdbbd",
        "department": "Editing",
        "job": "Editor"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 7232,
        "known_for_department": "Production",
        "name": "Sarah Halley Finn",
        "original_name": "Sarah Halley Finn",
        "popularity": 6.195,
        "profile_path": "/pI3OhmnHhXLEwuv0Vq6qJHivCJA.jpg",
        "credit_id": "648c887a559d22011c4b6092",
        "department": "Production",
        "job": "Casting"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 5551,
        "known_for_department": "Writing",
        "name": "Christopher Markus",
        "original_name": "Christopher Markus",
        "popularity": 4.424,
        "profile_path": "/7ooPNp0gnURxYkSSKF2etH7wpZP.jpg",
        "credit_id": "63c81dfa2f3b1700baaa9f04",
        "department": "Production",
        "job": "Executive Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 5552,
        "known_for_department": "Writing",
        "name": "Stephen McFeely",
        "original_name": "Stephen McFeely",
        "popularity": 4.113,
        "profile_path": "/hkn9D5L8TguJUmv8fXy5sHyMEtq.jpg",
        "credit_id": "63c81e02142ef100bd189aa1",
        "department": "Production",
        "job": "Executive Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 19271,
        "known_for_department": "Directing",
        "name": "Anthony Russo",
        "original_name": "Anthony Russo",
        "popularity": 8.589,
        "profile_path": "/xbINBnWn28YygYWUJ1aSAw0xPRv.jpg",
        "credit_id": "5eb109d3f74f5f001f9485bc",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 19271,
        "known_for_department": "Directing",
        "name": "Anthony Russo",
        "original_name": "Anthony Russo",
        "popularity": 8.589,
        "profile_path": "/xbINBnWn28YygYWUJ1aSAw0xPRv.jpg",
        "credit_id": "646810b92bcf6700e3ba3341",
        "department": "Writing",
        "job": "Original Story"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 19272,
        "known_for_department": "Directing",
        "name": "Joe Russo",
        "original_name": "Joe Russo",
        "popularity": 13.405,
        "profile_path": "/mgfu3w09c3NlG3KQtluw6kwC6ri.jpg",
        "credit_id": "5eb109c6d8e225001f3009b7",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 19272,
        "known_for_department": "Directing",
        "name": "Joe Russo",
        "original_name": "Joe Russo",
        "popularity": 13.405,
        "profile_path": "/mgfu3w09c3NlG3KQtluw6kwC6ri.jpg",
        "credit_id": "64680f6d2bcf67011bf2c0a7",
        "department": "Writing",
        "job": "Writer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 19272,
        "known_for_department": "Directing",
        "name": "Joe Russo",
        "original_name": "Joe Russo",
        "popularity": 13.405,
        "profile_path": "/mgfu3w09c3NlG3KQtluw6kwC6ri.jpg",
        "credit_id": "646810b42bcf6700fe5fde2e",
        "department": "Writing",
        "job": "Original Story"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 23401,
        "known_for_department": "Editing",
        "name": "Alex Rodríguez",
        "original_name": "Alex Rodríguez",
        "popularity": 1.4,
        "profile_path": null,
        "credit_id": "648c886d076ce800ad72b93f",
        "department": "Editing",
        "job": "Editor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 74568,
        "known_for_department": "Acting",
        "name": "Chris Hemsworth",
        "original_name": "Chris Hemsworth",
        "popularity": 82.305,
        "profile_path": "/jpurJ9jAcLCYjgHHfYF32m3zJYm.jpg",
        "credit_id": "63c81dbc70b44400e95a37f4",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 68217,
        "known_for_department": "Production",
        "name": "Eric Gitter",
        "original_name": "Eric Gitter",
        "popularity": 1.329,
        "profile_path": null,
        "credit_id": "63c81dd32f3b1700a0df34e8",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 113375,
        "known_for_department": "Sound",
        "name": "José E. Caldararo",
        "original_name": "José E. Caldararo",
        "popularity": 1.052,
        "profile_path": null,
        "credit_id": "648d5b8426346200eb75b7fd",
        "department": "Sound",
        "job": "Foley Supervisor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 227440,
        "known_for_department": "Sound",
        "name": "Henry Jackman",
        "original_name": "Henry Jackman",
        "popularity": 2.302,
        "profile_path": "/wJYFGHG5Vsh8cbiyiS8zpO2SMHb.jpg",
        "credit_id": "648c884e42bf0100c7faa0ba",
        "department": "Sound",
        "job": "Original Music Composer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 554888,
        "known_for_department": "Sound",
        "name": "Charles Maynes",
        "original_name": "Charles Maynes",
        "popularity": 1.84,
        "profile_path": null,
        "credit_id": "648d5b0042bf01011e72e3d8",
        "department": "Sound",
        "job": "Sound Effects Editor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1051722,
        "known_for_department": "Sound",
        "name": "Chris Goodes",
        "original_name": "Chris Goodes",
        "popularity": 0.617,
        "profile_path": null,
        "credit_id": "648d5a832f8d09013af98ee5",
        "department": "Sound",
        "job": "Sound Re-Recording Mixer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1077677,
        "known_for_department": "Sound",
        "name": "Tom Hodge",
        "original_name": "Tom Hodge",
        "popularity": 0.6,
        "profile_path": "/pPkIYkNUTGAM7KtS5SAiJnX0doh.jpg",
        "credit_id": "648d5ce826346200ae1b7071",
        "department": "Crew",
        "job": "Additional Music"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1090381,
        "known_for_department": "Sound",
        "name": "Evan Goldman",
        "original_name": "Evan Goldman",
        "popularity": 1.128,
        "profile_path": null,
        "credit_id": "648d5cc62f8d090100a9cc1b",
        "department": "Crew",
        "job": "Additional Music"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1104904,
        "known_for_department": "Directing",
        "name": "Benjamin Grayson",
        "original_name": "Benjamin Grayson",
        "popularity": 1.012,
        "profile_path": null,
        "credit_id": "63c81de9abdec0009432a706",
        "department": "Production",
        "job": "Executive Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1120883,
        "known_for_department": "Acting",
        "name": "Sam Hargrave",
        "original_name": "Sam Hargrave",
        "popularity": 28.611,
        "profile_path": "/mq7KgHiyuwFOvxuEg8p0Z30pybY.jpg",
        "credit_id": "614f652c140bad0061a81ba0",
        "department": "Directing",
        "job": "Director"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1120883,
        "known_for_department": "Acting",
        "name": "Sam Hargrave",
        "original_name": "Sam Hargrave",
        "popularity": 28.611,
        "profile_path": "/mq7KgHiyuwFOvxuEg8p0Z30pybY.jpg",
        "credit_id": "63c81dcc2f3b1700937fa901",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1193191,
        "known_for_department": "Production",
        "name": "Patrick Newall",
        "original_name": "Patrick Newall",
        "popularity": 2.475,
        "profile_path": "/dOGLRCvGb8mCXSjoDAq4l9Xroob.jpg",
        "credit_id": "63c81dc57a97ab00d3a69d4e",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1223099,
        "known_for_department": "Sound",
        "name": "Christopher T. Welch",
        "original_name": "Christopher T. Welch",
        "popularity": 0.722,
        "profile_path": null,
        "credit_id": "648d5b1f559d2200ad81da1f",
        "department": "Sound",
        "job": "Dialogue Editor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1299326,
        "known_for_department": "Art",
        "name": "Matt Wynne",
        "original_name": "Matt Wynne",
        "popularity": 0.652,
        "profile_path": null,
        "credit_id": "648c88cac3c891010ca41712",
        "department": "Art",
        "job": "Art Direction"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1334494,
        "known_for_department": "Art",
        "name": "Martina Ter-Akopowá",
        "original_name": "Martina Ter-Akopowá",
        "popularity": 0.619,
        "profile_path": null,
        "credit_id": "648c88d2c3c891014ebcda31",
        "department": "Art",
        "job": "Supervising Art Director"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1335122,
        "known_for_department": "Sound",
        "name": "Donald Flick",
        "original_name": "Donald Flick",
        "popularity": 1.108,
        "profile_path": null,
        "credit_id": "648d5aac2f8d09011d239b78",
        "department": "Sound",
        "job": "Sound Effects Editor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1346938,
        "known_for_department": "Sound",
        "name": "Stanomir Dragoş",
        "original_name": "Stanomir Dragoş",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d582e2f8d0900c66561c4",
        "department": "Sound",
        "job": "Production Sound Mixer"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1346957,
        "known_for_department": "Directing",
        "name": "Andra Barbuica",
        "original_name": "Andra Barbuica",
        "popularity": 2.082,
        "profile_path": null,
        "credit_id": "648d57f8c3c89100cad9ea2e",
        "department": "Directing",
        "job": "Script Supervisor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1357064,
        "known_for_department": "Camera",
        "name": "Greg Baldi",
        "original_name": "Greg Baldi",
        "popularity": 3.329,
        "profile_path": null,
        "credit_id": "648c8858c3c89100ae5025a0",
        "department": "Camera",
        "job": "Director of Photography"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1357339,
        "known_for_department": "Sound",
        "name": "Peter Mullen",
        "original_name": "Peter Mullen",
        "popularity": 1.38,
        "profile_path": null,
        "credit_id": "648d5ade2f8d090100a9caa5",
        "department": "Sound",
        "job": "Sound Effects Editor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1382731,
        "known_for_department": "Production",
        "name": "Jake Aust",
        "original_name": "Jake Aust",
        "popularity": 1.389,
        "profile_path": null,
        "credit_id": "63c81e0b70b44400e95a382b",
        "department": "Production",
        "job": "Executive Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1392718,
        "known_for_department": "Camera",
        "name": "Jasin Boland",
        "original_name": "Jasin Boland",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d57cb559d2200c5762e6e",
        "department": "Camera",
        "job": "Still Photographer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1400486,
        "known_for_department": "Crew",
        "name": "Tim Pedegana",
        "original_name": "Tim Pedegana",
        "popularity": 1.62,
        "profile_path": null,
        "credit_id": "648d56ffc2ff3d00ad0194e1",
        "department": "Crew",
        "job": "Post Production Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1405917,
        "known_for_department": "Production",
        "name": "Mike Larocca",
        "original_name": "Mike Larocca",
        "popularity": 2.689,
        "profile_path": null,
        "credit_id": "63c81da5abdec0009432a6ef",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1408802,
        "known_for_department": "Crew",
        "name": "Pavel Sagner",
        "original_name": "Pavel Sagner",
        "popularity": 0.716,
        "profile_path": null,
        "credit_id": "648d58d5559d22011c4bd993",
        "department": "Visual Effects",
        "job": "Special Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1410154,
        "known_for_department": "Visual Effects",
        "name": "Martin Prýca",
        "original_name": "Martin Prýca",
        "popularity": 0.828,
        "profile_path": null,
        "credit_id": "648d58b0c3c89100cad9eaa5",
        "department": "Visual Effects",
        "job": "Special Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1423004,
        "known_for_department": "Sound",
        "name": "David Metzner",
        "original_name": "David Metzner",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5ca4c3c891012d5d4c69",
        "department": "Sound",
        "job": "Music Editor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1458995,
        "known_for_department": "Sound",
        "name": "Mark Binder",
        "original_name": "Mark Binder",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5a4b559d2200e205dca2",
        "department": "Sound",
        "job": "Sound Designer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1458995,
        "known_for_department": "Sound",
        "name": "Mark Binder",
        "original_name": "Mark Binder",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5a2a559d2200ad81d97b",
        "department": "Sound",
        "job": "Supervising Sound Editor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1458995,
        "known_for_department": "Sound",
        "name": "Mark Binder",
        "original_name": "Mark Binder",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5a3e559d2200e205dc98",
        "department": "Sound",
        "job": "Sound Re-Recording Mixer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1472650,
        "known_for_department": "Production",
        "name": "Peter Schwerin",
        "original_name": "Peter Schwerin",
        "popularity": 0.753,
        "profile_path": null,
        "credit_id": "63c81dd97a97ab008058028d",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1503225,
        "known_for_department": "Art",
        "name": "Carlo Crescini",
        "original_name": "Carlo Crescini",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c8899c2ff3d00ad0125c5",
        "department": "Art",
        "job": "Art Direction"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1569396,
        "known_for_department": "Production",
        "name": "Krista Husar",
        "original_name": "Krista Husar",
        "popularity": 1.038,
        "profile_path": null,
        "credit_id": "648c8885c2ff3d011cb8950e",
        "department": "Production",
        "job": "Casting"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1580853,
        "known_for_department": "Editing",
        "name": "Matthew G. Carson",
        "original_name": "Matthew G. Carson",
        "popularity": 0.84,
        "profile_path": null,
        "credit_id": "648d59c7559d2200ad81d93e",
        "department": "Editing",
        "job": "Additional Editing"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1751775,
        "known_for_department": "Writing",
        "name": "Angela Russo-Otstot",
        "original_name": "Angela Russo-Otstot",
        "popularity": 1.807,
        "profile_path": null,
        "credit_id": "63c81db370b4440094a4f65a",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1816359,
        "known_for_department": "Art",
        "name": "Tony Drew",
        "original_name": "Tony Drew",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c88a342bf0100e49daa1c",
        "department": "Art",
        "job": "Art Direction"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1816360,
        "known_for_department": "Art",
        "name": "Andrew Kattie",
        "original_name": "Andrew Kattie",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c8919c3c89100eb31e25a",
        "department": "Art",
        "job": "Assistant Art Director"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1844182,
        "known_for_department": "Production",
        "name": "Steven V. Scavelli",
        "original_name": "Steven V. Scavelli",
        "popularity": 0.985,
        "profile_path": null,
        "credit_id": "63c81df3abdec000e213bd10",
        "department": "Production",
        "job": "Executive Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2012608,
        "known_for_department": "Sound",
        "name": "Alex Belcher",
        "original_name": "Alex Belcher",
        "popularity": 2.268,
        "profile_path": "/RzVxdQXIozrF6BwufFG1lxbVg.jpg",
        "credit_id": "648c8845076ce80144258f8b",
        "department": "Sound",
        "job": "Original Music Composer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2087802,
        "known_for_department": "Production",
        "name": "Quinn Kawata",
        "original_name": "Quinn Kawata",
        "popularity": 1.592,
        "profile_path": null,
        "credit_id": "648d59e9263462014e578a1d",
        "department": "Production",
        "job": "Post Production Coordinator"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2213678,
        "known_for_department": "Sound",
        "name": "Xiang Li",
        "original_name": "Xiang Li",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5ac6c2ff3d00ffbaf06b",
        "department": "Sound",
        "job": "Sound Effects Editor"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 2354363,
        "known_for_department": "Costume & Make-Up",
        "name": "Rebekka Jónsdóttir",
        "original_name": "Rebekka Jónsdóttir",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c88dfc3c89100eb31e23e",
        "department": "Costume & Make-Up",
        "job": "Costume Design"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2395143,
        "known_for_department": "Art",
        "name": "Charlotte Anthony",
        "original_name": "Charlotte Anthony",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c88f926346200eb75420f",
        "department": "Art",
        "job": "Set Designer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2441145,
        "known_for_department": "Sound",
        "name": "Gabriel Santamaría",
        "original_name": "Gabriel Santamaría",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5c20c3c891010ca48616",
        "department": "Sound",
        "job": "Foley Artist"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2613695,
        "known_for_department": "Writing",
        "name": "Ande Parks",
        "original_name": "Ande Parks",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "646810ac006b010147e97a24",
        "department": "Writing",
        "job": "Original Story"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2613695,
        "known_for_department": "Writing",
        "name": "Ande Parks",
        "original_name": "Ande Parks",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63c81d452f3b1700a0df34c0",
        "department": "Writing",
        "job": "Graphic Novel"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2614090,
        "known_for_department": "Crew",
        "name": "Fernando León González",
        "original_name": "Fernando León González",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63c81d56c5c1ef00825b19c4",
        "department": "Crew",
        "job": "Graphic Novel Illustrator"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2614264,
        "known_for_department": "Crew",
        "name": "Jon Monroe",
        "original_name": "Jon Monroe",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5d0c2f8d09013af99079",
        "department": "Crew",
        "job": "Additional Music"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2628622,
        "known_for_department": "Sound",
        "name": "Emilio Iglesias",
        "original_name": "Emilio Iglesias",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5bd52f8d0900c6656400",
        "department": "Sound",
        "job": "Foley Mixer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2773912,
        "known_for_department": "Production",
        "name": "Sunny Sun",
        "original_name": "Sunny Sun",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d577942bf010101be0fc9",
        "department": "Crew",
        "job": "Fight Choreographer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3008465,
        "known_for_department": "Sound",
        "name": "Paula Troia",
        "original_name": "Paula Troia",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5c6ac3c891012d5d4c45",
        "department": "Sound",
        "job": "Foley Artist"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3111968,
        "known_for_department": "Art",
        "name": "Pavel Krejci",
        "original_name": "Pavel Krejci",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c88af26346200ca195a99",
        "department": "Art",
        "job": "Art Direction"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3176527,
        "known_for_department": "Sound",
        "name": "Vu Le",
        "original_name": "Vu Le",
        "popularity": 1.4,
        "profile_path": null,
        "credit_id": "648d5b5326346200ca19c916",
        "department": "Sound",
        "job": "ADR Mixer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3307010,
        "known_for_department": "Art",
        "name": "Natálie Kalendová",
        "original_name": "Natálie Kalendová",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c890ec3c89100ae5025f6",
        "department": "Art",
        "job": "Set Designer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3307013,
        "known_for_department": "Costume & Make-Up",
        "name": "Jennifer Lander",
        "original_name": "Jennifer Lander",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c88e9c3c89100eb31e248",
        "department": "Costume & Make-Up",
        "job": "Costume Design"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3425539,
        "known_for_department": "Art",
        "name": "Dan Sucharipa",
        "original_name": "Dan Sucharipa",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c88b8559d2200ff10017f",
        "department": "Art",
        "job": "Art Direction"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3604096,
        "known_for_department": "Sound",
        "name": "Jakob Weber",
        "original_name": "Jakob Weber",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5b3cc3c891014ebd500d",
        "department": "Sound",
        "job": "Dialogue Editor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 3870579,
        "known_for_department": "Art",
        "name": "Michal Motyčka",
        "original_name": "Michal Motyčka",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c893942bf010101bd9a7c",
        "department": "Art",
        "job": "Set Dresser"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3887122,
        "known_for_department": "Sound",
        "name": "Facundo Pacheco Acri",
        "original_name": "Facundo Pacheco Acri",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5bac42bf0100ae30fe6b",
        "department": "Sound",
        "job": "Foley Mixer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3946854,
        "known_for_department": "Sound",
        "name": "Gabriel Emmanuel Kevicky",
        "original_name": "Gabriel Emmanuel Kevicky",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5c3dc3c891010ca48625",
        "department": "Sound",
        "job": "Foley Artist"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 4064982,
        "known_for_department": "Sound",
        "name": "Julian Fernandez Arizzi",
        "original_name": "Julian Fernandez Arizzi",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648d5bfc2f8d09013af98fda",
        "department": "Sound",
        "job": "Foley Mixer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 4115589,
        "known_for_department": "Art",
        "name": "Aisha K. Aziz",
        "original_name": "Aisha K. Aziz",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c8902c2ff3d00ad0125f6",
        "department": "Art",
        "job": "Set Designer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 4115590,
        "known_for_department": "Art",
        "name": "Vanda Martínková",
        "original_name": "Vanda Martínková",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "648c892e076ce800e7438fe4",
        "department": "Art",
        "job": "Set Designer"
      }
    ]
  },
  "keywords": {
    "keywords": [
      {
        "id": 3070,
        "name": "mercenary"
      },
      {
        "id": 9663,
        "name": "sequel"
      },
      {
        "id": 11107,
        "name": "rescue mission"
      },
      {
        "id": 11440,
        "name": "long take"
      },
      {
        "id": 18712,
        "name": "based on graphic novel"
      }
    ]
  },
  "recommendations": {
    "page": 1,
    "results": [
      {
        "adult": false,
        "backdrop_path": "/b8Ylp5q46U2u52QxTmDzXwtnQR.jpg",
        "id": 445954,
        "title": "Acts of Vengeance",
        "original_language": "en",
        "original_title": "Acts of Vengeance",
        "overview": "A fast-talking lawyer transforms his body and takes a vow of silence, not to be broken until he finds out who killed his wife and daughter and has his revenge.",
        "poster_path": "/r5o6vWPYOQs6bv91gQ8kQs2zQYl.jpg",
        "media_type": "movie",
        "genre_ids": [
          53,
          28,
          18
        ],
        "popularity": 20.297,
        "release_date": "2017-10-27",
        "video": false,
        "vote_average": 5.919,
        "vote_count": 496
      },
      {
        "adult": false,
        "backdrop_path": "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
        "id": 385687,
        "title": "Fast X",
        "original_language": "en",
        "original_title": "Fast X",
        "overview": "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
        "poster_path": "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
        "media_type": "movie",
        "genre_ids": [
          28,
          80,
          53
        ],
        "popularity": 4714.532,
        "release_date": "2023-05-17",
        "video": false,
        "vote_average": 7.323,
        "vote_count": 2327
      },
      {
        "adult": false,
        "backdrop_path": "/fEe2csLOUsTyaLdCccVJfFeJzhx.jpg",
        "id": 298618,
        "title": "The Flash",
        "original_language": "en",
        "original_title": "The Flash",
        "overview": "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
        "poster_path": "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
        "media_type": "movie",
        "genre_ids": [
          878,
          28,
          12
        ],
        "popularity": 1045.9,
        "release_date": "2023-06-13",
        "video": false,
        "vote_average": 6.728,
        "vote_count": 714
      },
      {
        "adult": false,
        "backdrop_path": "/gMJngTNfaqCSCqGD4y8lVMZXKDn.jpg",
        "id": 640146,
        "title": "Ant-Man and the Wasp: Quantumania",
        "original_language": "en",
        "original_title": "Ant-Man and the Wasp: Quantumania",
        "overview": "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
        "poster_path": "/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
        "media_type": "movie",
        "genre_ids": [
          28,
          12,
          878
        ],
        "popularity": 757.97,
        "release_date": "2023-02-15",
        "video": false,
        "vote_average": 6.482,
        "vote_count": 3448
      },
      {
        "adult": false,
        "backdrop_path": "/igXrblWrU1uaC09VKyquHHSebr.jpg",
        "id": 717930,
        "title": "Kandahar",
        "original_language": "en",
        "original_title": "Kandahar",
        "overview": "After his mission is exposed, an undercover CIA operative stuck deep in hostile territory in Afghanistan must fight his way out, alongside his Afghan translator, to an extraction point in Kandahar, all whilst avoiding elite enemy forces and foreign spies tasked with hunting them down.",
        "poster_path": "/lCanGgsqF4xD2WA5NF8PWeT3IXd.jpg",
        "media_type": "movie",
        "genre_ids": [
          28,
          53
        ],
        "popularity": 191.261,
        "release_date": "2023-05-25",
        "video": false,
        "vote_average": 6.3,
        "vote_count": 179
      },
      {
        "adult": false,
        "backdrop_path": "/qGzr1S9sMYfVF3rPzdUmx5OY2IO.jpg",
        "id": 1128382,
        "title": "Americonned",
        "original_language": "en",
        "original_title": "Americonned",
        "overview": "The super-rich determines virtually every aspect of the lives of the other 90% of Americans. This film examines the hidden struggles of American families, the calculated political maneuvers of the elite, and the long overdue uprising of American workers. With affection for the middle-class and the outrageous attempt to color them as lazy, the film explores the question: How do we make sure workers are paid what they are worth, instead of believing they are only worth what they are paid?",
        "poster_path": "/gO3xk77qhZT9R5Vh07DKob4xk1V.jpg",
        "media_type": "movie",
        "genre_ids": [
          99
        ],
        "popularity": 5.31,
        "release_date": "2023-06-09",
        "video": true,
        "vote_average": 2,
        "vote_count": 1
      },
      {
        "adult": false,
        "backdrop_path": "/o8KsNw4WB8t0YYhSftoWdyeSfj6.jpg",
        "id": 1084028,
        "title": "The Love Club: Tara’s Tune",
        "original_language": "en",
        "original_title": "The Love Club: Tara’s Tune",
        "overview": "Tara has always considered herself to be a free spirit. Moreover, the talented singer doesn’t seek love. Instead, she has her friends in The Love Club.",
        "poster_path": "/bKe6vUEOTxwlUu3VHfZrmcvkVSE.jpg",
        "media_type": "movie",
        "genre_ids": [
          10770,
          35,
          10749
        ],
        "popularity": 6.653,
        "release_date": "2023-02-22",
        "video": false,
        "vote_average": 6.7,
        "vote_count": 3
      },
      {
        "adult": false,
        "backdrop_path": "/6BI1XjPNT5VYEJ4vXkdyuiKLMYt.jpg",
        "id": 1119173,
        "title": "A Beautiful Life",
        "original_language": "da",
        "original_title": "A Beautiful Life",
        "overview": "When a young fisherman with a hidden talent gets discovered by a music producer, he must decide if he's ready to open himself up to stardom — and love.",
        "poster_path": "/x6PvT4HAkK7phdj54Zao8rY5oBT.jpg",
        "media_type": "movie",
        "genre_ids": [
          18,
          10402,
          10749
        ],
        "popularity": 73.431,
        "release_date": "2023-06-01",
        "video": false,
        "vote_average": 6.965,
        "vote_count": 128
      },
      {
        "adult": false,
        "backdrop_path": "/1R6cvRtZgsYCkh8UFuWFN33xBP4.jpg",
        "id": 545609,
        "title": "Extraction",
        "original_language": "en",
        "original_title": "Extraction",
        "overview": "Tyler Rake, a fearless mercenary who offers his services on the black market, embarks on a dangerous mission when he is hired to rescue the kidnapped son of a Mumbai crime lord.",
        "poster_path": "/nygOUcBKPHFTbxsYRFZVePqgPK6.jpg",
        "media_type": "movie",
        "genre_ids": [
          28,
          53
        ],
        "popularity": 273.409,
        "release_date": "2020-04-24",
        "video": false,
        "vote_average": 7.348,
        "vote_count": 5259
      },
      {
        "adult": false,
        "backdrop_path": "/qWQSnedj0LCUjWNp9fLcMtfgadp.jpg",
        "id": 667538,
        "title": "Transformers: Rise of the Beasts",
        "original_language": "en",
        "original_title": "Transformers: Rise of the Beasts",
        "overview": "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
        "poster_path": "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
        "media_type": "movie",
        "genre_ids": [
          28,
          12,
          878
        ],
        "popularity": 1869.826,
        "release_date": "2023-06-06",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 540
      },
      {
        "adult": false,
        "backdrop_path": "/94ZtdIXKR5nQPOC41xBw4aLDbjX.jpg",
        "id": 1031778,
        "title": "On Sacred Ground",
        "original_language": "en",
        "original_title": "On Sacred Ground",
        "overview": "Based on the true events during the 2016 construction of the Dakota Access Pipeline that runs through the Standing Rock Indian Reservation in North Dakota on land that is owned by the Lakota “Sioux” Tribe. The film follows Daniel, a journalist and Afghanistan War military veteran, and Elliot, an oil company executive, who find themselves on opposite sides of the fight during the construction of the contentious pipeline.",
        "poster_path": "/3kC2EXrjIgTxAP8EvwqVKGf1rET.jpg",
        "media_type": "movie",
        "genre_ids": [
          18
        ],
        "popularity": 8.131,
        "release_date": "2023-01-13",
        "video": false,
        "vote_average": 5.333,
        "vote_count": 6
      },
      {
        "adult": false,
        "backdrop_path": "/osnvZffaZymubHiBkOsIFd8Y3Re.jpg",
        "id": 986070,
        "title": "The Wrath of Becky",
        "original_language": "en",
        "original_title": "The Wrath of Becky",
        "overview": "Two years after she escaped a violent attack on her family, 16-year-old Becky attempts to rebuild her life in the care of an older woman -- a kindred spirit named Elena. However, when a violent group known as the Noble Men break into their home, attack them and take their beloved dog, Becky must return to her old ways to protect herself and her loved ones.",
        "poster_path": "/3LShl6EwqptKIVq6NWOZ0FbZHEe.jpg",
        "media_type": "movie",
        "genre_ids": [
          28,
          27,
          53
        ],
        "popularity": 1201.783,
        "release_date": "2023-05-26",
        "video": false,
        "vote_average": 6.754,
        "vote_count": 61
      },
      {
        "adult": false,
        "backdrop_path": "/35OoC3JxHXrAOg4FAa2DrPCzUX9.jpg",
        "id": 1010581,
        "title": "My Fault",
        "original_language": "es",
        "original_title": "Culpa mía",
        "overview": "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
        "poster_path": "/w46Vw536HwNnEzOa7J24YH9DPRS.jpg",
        "media_type": "movie",
        "genre_ids": [
          10749,
          18
        ],
        "popularity": 1212.697,
        "release_date": "2023-06-08",
        "video": false,
        "vote_average": 8.26,
        "vote_count": 1000
      },
      {
        "adult": false,
        "backdrop_path": "/ErGV8yWaZNYVSK6xePCkvNMEPS.jpg",
        "id": 1121156,
        "title": "Pocket Dial Murder",
        "original_language": "en",
        "original_title": "Pocket Dial Murder",
        "overview": "Stacey receives a pocket dial from her husband, Jeff, where she hears the sudden death of a woman on the other end. When Jeff comes home, he says he lost his phone she doesn’t know what to think. Could Stacey be married to a murderer?",
        "poster_path": "/qn4AHNUtVjEsLDwURKBhPg90tkS.jpg",
        "media_type": "movie",
        "genre_ids": [
          10770,
          53,
          18,
          80
        ],
        "popularity": 11.894,
        "release_date": "2023-06-16",
        "video": false,
        "vote_average": 6.3,
        "vote_count": 3
      },
      {
        "adult": false,
        "backdrop_path": "/rzuWyiINQFPWWFEXTItpUzSEWJD.jpg",
        "id": 1138635,
        "title": "Nigel Ng: The HAIYAA Special",
        "original_language": "en",
        "original_title": "Nigel Ng: The HAIYAA Special",
        "overview": "Uncle Roger and his nephew Nigel Ng present The HAIYAA Special, filmed on their sold out world tour. In this two-part special, Uncle Roger roasts the crowd, while Nigel delivers side-splitting commentary on life and culture. Allergic to MSG and inappropriate jokes? You've been warned.",
        "poster_path": "/nxF1JPmOkVG1KMZGlkoVKFWMHnD.jpg",
        "media_type": "movie",
        "genre_ids": [
          35
        ],
        "popularity": 4.146,
        "release_date": "2023-02-04",
        "video": false,
        "vote_average": 7.5,
        "vote_count": 2
      },
      {
        "adult": false,
        "backdrop_path": "/gBZwcIlWcW8Hmc7ZDo7jxOwDkFa.jpg",
        "id": 155820,
        "title": "A Bomb Was Stolen",
        "original_language": "ro",
        "original_title": "S-a furat o bomba",
        "overview": "A dialogue free Romanian science-fiction spy-comedy that draws upon farce, satire and surrealism as it subversively deconstructs the spy thriller with the protagonist's accidental discovery of a nuclear suitcase bomb and the subsequent fight over ownership between the rival powers of the criminals and the military.",
        "poster_path": "/rDWNXbEMrGL8V81tUGw3UbdOi7N.jpg",
        "media_type": "movie",
        "genre_ids": [
          878,
          35,
          14
        ],
        "popularity": 1.518,
        "release_date": "1961-08-11",
        "video": false,
        "vote_average": 5.909,
        "vote_count": 11
      },
      {
        "adult": false,
        "backdrop_path": "/q09Gsi9gPBFZOO3q2YKExlggXVv.jpg",
        "id": 1014390,
        "title": "Bloody Daddy",
        "original_language": "hi",
        "original_title": "Bloody Daddy",
        "overview": "Sumair Azad, a dirty cop and his friend, Jaggi, steal Sikandar Chowdhary's cocaine bag. As a result, Sikandar kidnaps Sumair's son, but things take a turn when he loses the cocaine bag as he faces off Gurugram’s drug lords, a crime boss, murderous narcs and straight cops on one fateful night.",
        "poster_path": "/gX8k6oKpIsWHpfWNz3Bu4wUuliA.jpg",
        "media_type": "movie",
        "genre_ids": [
          28,
          80,
          53
        ],
        "popularity": 8.977,
        "release_date": "2023-06-09",
        "video": false,
        "vote_average": 6.833,
        "vote_count": 11
      },
      {
        "adult": false,
        "backdrop_path": "/mAZDQWiytKNXL1ZKsstmbhYJzsx.jpg",
        "id": 938553,
        "title": "Khun Pan 3",
        "original_language": "th",
        "original_title": "ขุนพันธ์ 3",
        "overview": "In the year 1950, the country was affected by the war. Crowds of thieves are still plentiful everywhere. Khun Pan, a police buster who adheres to the correctness, has therefore been called back to perform a mission to hunt down 2 thieves, namely Bandit Mahesuan and Bandit Dam, a magical thief. A strong man who is energetic and challenges the power of the state without anyone ever having access to him. Leading to Khun Phan's stepping on the tiger again. In the midst of these evil tigers who want to kill And are ready to judge the invulnerable buster with death.",
        "poster_path": "/xaspbqQ6r43MPEpQWUwTYqALqOy.jpg",
        "media_type": "movie",
        "genre_ids": [
          28,
          14,
          53
        ],
        "popularity": 6.876,
        "release_date": "2023-03-02",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 7
      },
      {
        "adult": false,
        "backdrop_path": "/oRCmzBhspg2nfx9JtcAsWzCz0G9.jpg",
        "id": 1119087,
        "title": "Jimmy O. Yang: Guess How Much?",
        "original_language": "en",
        "original_title": "Jimmy O. Yang: Guess How Much?",
        "overview": "Jimmy O. Yang's first global stand-up special. The comedian delves into various topics including love languages, loser friends, and negotiating with his Asian parents.",
        "poster_path": "/cFAFtCrSb9JzxmUhP9SLC7hV1be.jpg",
        "media_type": "movie",
        "genre_ids": [
          35
        ],
        "popularity": 3.811,
        "release_date": "2023-05-02",
        "video": false,
        "vote_average": 6.375,
        "vote_count": 4
      },
      {
        "adult": false,
        "backdrop_path": "/u0HBu7x5cwFe7BN7ANgYK98rgXc.jpg",
        "id": 717082,
        "title": "Stan Lee",
        "original_language": "en",
        "original_title": "Stan Lee",
        "overview": "Celebrate the legacy of Stan Lee as the co-creator of such legendary characters as Fantastic Four, Iron Man, the X-Men, The Avengers, and hundreds more.",
        "poster_path": "/iWBOKF0yl7pHK9y8fqRIBqf9fOJ.jpg",
        "media_type": "movie",
        "genre_ids": [
          99
        ],
        "popularity": 47.033,
        "release_date": "2023-06-16",
        "video": false,
        "vote_average": 7.109,
        "vote_count": 32
      },
      {
        "adult": false,
        "backdrop_path": "/p6M56sIXlF2MBDQlTlL8yCnWgQl.jpg",
        "id": 759297,
        "title": "The Housemaid",
        "original_language": "tl",
        "original_title": "The Housemaid",
        "overview": "Daisy's task as a new maid to a wealthy family is to watch over a young kid, but unknowingly she's being watched by the kid's father. When temptation kicks in Daisy and the wealthy family's lives start to shatter in pieces.",
        "poster_path": "/6QgSlS0IV9jlDadjdVrrN4quqEM.jpg",
        "media_type": "movie",
        "genre_ids": [
          53
        ],
        "popularity": 7.151,
        "release_date": "2021-09-10",
        "video": false,
        "vote_average": 5.1,
        "vote_count": 8
      }
    ],
    "total_pages": 2,
    "total_results": 40
  },
  "similar": {
    "page": 1,
    "results": [
      {
        "adult": false,
        "backdrop_path": "/uMSxXLfH7v30gRNBqsQaSP3yqX5.jpg",
        "genre_ids": [
          16,
          35,
          10751
        ],
        "id": 438148,
        "original_language": "en",
        "original_title": "Minions: The Rise of Gru",
        "overview": "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
        "popularity": 162.761,
        "poster_path": "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
        "release_date": "2022-06-29",
        "title": "Minions: The Rise of Gru",
        "video": false,
        "vote_average": 7.406,
        "vote_count": 2916
      },
      {
        "adult": false,
        "backdrop_path": "/gkxSIlZPEwGPimQ8TEE8C52cOSO.jpg",
        "genre_ids": [
          16,
          35,
          10751,
          12
        ],
        "id": 8355,
        "original_language": "en",
        "original_title": "Ice Age: Dawn of the Dinosaurs",
        "overview": "Times are changing for Manny the moody mammoth, Sid the motor mouthed sloth and Diego the crafty saber-toothed tiger. Life heats up for our heroes when they meet some new and none-too-friendly neighbors – the mighty dinosaurs.",
        "popularity": 80.266,
        "poster_path": "/cXOLaxcNjNAYmEx1trZxOTKhK3Q.jpg",
        "release_date": "2009-06-26",
        "title": "Ice Age: Dawn of the Dinosaurs",
        "video": false,
        "vote_average": 6.726,
        "vote_count": 7537
      },
      {
        "adult": false,
        "backdrop_path": "/sAFqN4bDfGUBgS6h323F7YcwqPe.jpg",
        "genre_ids": [
          28,
          35,
          53
        ],
        "id": 8460,
        "original_language": "en",
        "original_title": "The Skulls II",
        "overview": "After joining the Skulls, Ryan Sommers (Robin Dunne) is warned not to betray any secrets about the organization or its high-powered members. However, when Ryan witnesses a murder within the Skulls' private chambers, he finds that the closer he gets to revealing the truth - the more dangerous life becomes.",
        "popularity": 4.427,
        "poster_path": "/h6atL0SP5qg6TXOXy9DklZgObn2.jpg",
        "release_date": "2002-04-09",
        "title": "The Skulls II",
        "video": false,
        "vote_average": 4.8,
        "vote_count": 64
      },
      {
        "adult": false,
        "backdrop_path": "/a8UAXIEf83pyvP0dBhnUIzvEYmE.jpg",
        "genre_ids": [
          878,
          28,
          12
        ],
        "id": 8536,
        "original_language": "en",
        "original_title": "Superman II",
        "overview": "Three escaped criminals from the planet Krypton test the Man of Steel's mettle. Led by General Zod, the Kryptonians take control of the White House and partner with Lex Luthor to destroy Superman and rule the world. But Superman, who attempts to make himself human in order to get closer to Lois, realizes he has a responsibility to save the planet.",
        "popularity": 21.988,
        "poster_path": "/jw0tYFCbzjBN8SIhvRC2kdh7pzh.jpg",
        "release_date": "1980-12-04",
        "title": "Superman II",
        "video": false,
        "vote_average": 6.734,
        "vote_count": 2020
      },
      {
        "adult": false,
        "backdrop_path": null,
        "genre_ids": [
          18,
          36
        ],
        "id": 260830,
        "original_language": "hu",
        "original_title": "Allegro Barbaro",
        "overview": "Zsadányi flees from the authorities with his goddaughter, Bankós Mari, and they escape into the forest. The film then skips ahead thirty-fold years: Zsadány and Mari are now lovers, with the sound of war in the background halting their romance. The old friends of Zsadányi have joined with the Nazis, and the landowner living with his peasants in a socialist community grows distant from them. Zsadányi is held responsible for political problems in the country, and will pay with his life.",
        "popularity": 1.323,
        "poster_path": "/tdCUhWDJM7Y2U6dc840FTEDTALj.jpg",
        "release_date": "1979-10-11",
        "title": "Allegro Barbaro",
        "video": false,
        "vote_average": 6.6,
        "vote_count": 4
      },
      {
        "adult": false,
        "backdrop_path": "/dgQPsVodCzvVSQdsvPysuWmFPsX.jpg",
        "genre_ids": [
          28,
          12,
          10751,
          14,
          878
        ],
        "id": 6499,
        "original_language": "en",
        "original_title": "Turbo: A Power Rangers Movie",
        "overview": "The legendary Power Rangers must stop the evil space pirate Divatox from releasing the powerful Maligore from his volcanic imprisonment on the island of Muranthias, where only the kindly wizard Lerigot has the key to release him. The hope of victory lies in the Ranger's incredible new Turbo powers and powerful Turbo Zords.",
        "popularity": 20.994,
        "poster_path": "/deaDBDldND9PzCZ3mmsF0FxVq3P.jpg",
        "release_date": "1997-03-27",
        "title": "Turbo: A Power Rangers Movie",
        "video": false,
        "vote_average": 5.8,
        "vote_count": 248
      },
      {
        "adult": false,
        "backdrop_path": "/jEuwsmFS8JPzkDIhRL3B2BVYbU4.jpg",
        "genre_ids": [
          12,
          28,
          53,
          878
        ],
        "id": 8810,
        "original_language": "en",
        "original_title": "Mad Max 2",
        "overview": "Max Rockatansky returns as the heroic loner who drives the dusty roads of a postapocalyptic Australian Outback in an unending search for gasoline. Arrayed against him and the other scraggly defendants of a fuel-depot encampment are the bizarre warriors commanded by the charismatic Lord Humungus, a violent leader whose scruples are as barren as the surrounding landscape.",
        "popularity": 29.519,
        "poster_path": "/dhVekfpaCW3QavAwGYbaQig87Xc.jpg",
        "release_date": "1981-12-24",
        "title": "Mad Max 2",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 3214
      },
      {
        "adult": false,
        "backdrop_path": "/isFQiBiBiz4Xyx22sTs6CR1scL3.jpg",
        "genre_ids": [
          28,
          53
        ],
        "id": 8845,
        "original_language": "en",
        "original_title": "Under Siege",
        "overview": "Disgruntled ex-CIA operative Strannix, his assistant Krill and their group of terrorists seize the battleship with nuclear blackmail in mind. They've planned for every contingency but ignore the ship's cook, former Navy SEAL Casey Ryback -- an error that could be fatal.",
        "popularity": 19.744,
        "poster_path": "/myHxm9p8fhEsXyaLO6DawYJKolg.jpg",
        "release_date": "1992-10-08",
        "title": "Under Siege",
        "video": false,
        "vote_average": 6.248,
        "vote_count": 1331
      },
      {
        "adult": false,
        "backdrop_path": "/fStLMyjMzIGOch0lCgAyZ0mqwly.jpg",
        "genre_ids": [
          12,
          18,
          28,
          10749,
          10751
        ],
        "id": 8856,
        "original_language": "en",
        "original_title": "The Karate Kid Part II",
        "overview": "After discovering that his father is at death's door, Mr. Miyagi sets out to Japan, to see him with Daniel. Upon arriving, Miyagi must confront an old rival. Meanwhile, Daniel encounters a new love, and some new enemies.",
        "popularity": 27.584,
        "poster_path": "/k0OwgRR6PNu7h3SiqpCbRdZWNaG.jpg",
        "release_date": "1986-06-18",
        "title": "The Karate Kid Part II",
        "video": false,
        "vote_average": 6.262,
        "vote_count": 1914
      },
      {
        "adult": false,
        "backdrop_path": "/9X7YweCJw3q8Mcf6GadxReFEksM.jpg",
        "genre_ids": [
          28,
          18,
          878
        ],
        "id": 263115,
        "original_language": "en",
        "original_title": "Logan",
        "overview": "In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan's attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",
        "popularity": 58.979,
        "poster_path": "/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
        "release_date": "2017-02-28",
        "title": "Logan",
        "video": false,
        "vote_average": 7.815,
        "vote_count": 17867
      },
      {
        "adult": false,
        "backdrop_path": "/f34pJJrma66PKPsdDpBTTbBz8pB.jpg",
        "genre_ids": [
          27,
          14,
          28,
          878
        ],
        "id": 262848,
        "original_language": "en",
        "original_title": "Phantasm: Ravager",
        "overview": "Brothers Mike and Jody join family friend Reggie to battle the Tall Man and his evil minions from another dimension, for the final time.",
        "popularity": 8.42,
        "poster_path": "/zfZPcIYyVX2LW799SWxLFcTWQxa.jpg",
        "release_date": "2016-10-07",
        "title": "Phantasm: Ravager",
        "video": false,
        "vote_average": 5,
        "vote_count": 134
      },
      {
        "adult": false,
        "backdrop_path": "/uhBTaysiWU3dIQFHiVWXHuqO4OZ.jpg",
        "genre_ids": [
          28,
          18,
          53
        ],
        "id": 9331,
        "original_language": "en",
        "original_title": "Clear and Present Danger",
        "overview": "CIA Analyst Jack Ryan is drawn into an illegal war fought by the US government against a Colombian drug cartel.",
        "popularity": 22.227,
        "poster_path": "/6xTM8FPxrLRYwz6I3fqtwh7xybs.jpg",
        "release_date": "1994-08-03",
        "title": "Clear and Present Danger",
        "video": false,
        "vote_average": 6.613,
        "vote_count": 1287
      },
      {
        "adult": false,
        "backdrop_path": "/br1zDvgmBPa1EbBrUmEDaXXgykq.jpg",
        "genre_ids": [
          28,
          12,
          878
        ],
        "id": 9355,
        "original_language": "en",
        "original_title": "Mad Max Beyond Thunderdome",
        "overview": "Mad Max becomes a pawn in a decadent oasis of a technological society, and when exiled, becomes the deliverer of a colony of children.",
        "popularity": 22.944,
        "poster_path": "/jJlxcEVVUHnrUeEkQ0077VeHQpb.jpg",
        "release_date": "1985-06-29",
        "title": "Mad Max Beyond Thunderdome",
        "video": false,
        "vote_average": 6.2,
        "vote_count": 2475
      },
      {
        "adult": false,
        "backdrop_path": "/wVTvfxz53pDqrIvbrxhVdKcLhip.jpg",
        "genre_ids": [
          28,
          12,
          878,
          53
        ],
        "id": 9381,
        "original_language": "en",
        "original_title": "Babylon A.D.",
        "overview": "A veteran-turned-mercenary is hired to take a young woman with a secret from post-apocalyptic Eastern Europe to New York City.",
        "popularity": 14.952,
        "poster_path": "/kt9nqD0uOar8IVE9191HXhWOXKI.jpg",
        "release_date": "2008-08-20",
        "title": "Babylon A.D.",
        "video": false,
        "vote_average": 5.565,
        "vote_count": 1818
      },
      {
        "adult": false,
        "backdrop_path": "/s6cgAveWCam2hYgdPhD3WbrjSBt.jpg",
        "genre_ids": [
          28,
          53,
          80,
          14,
          9648,
          27
        ],
        "id": 9456,
        "original_language": "en",
        "original_title": "The Crow: Salvation",
        "overview": "Alex Corvis returns to the world of the living to avenge the murder of his girlfriend, who he was wrongly accused of killing. But first he must uncover the truth about who really killed her.",
        "popularity": 15.659,
        "poster_path": "/zIaYOfyMlBbfZzPQRv8gUuDqa2R.jpg",
        "release_date": "2000-01-23",
        "title": "The Crow: Salvation",
        "video": false,
        "vote_average": 5.4,
        "vote_count": 282
      },
      {
        "adult": false,
        "backdrop_path": "/baJHUXBcoaHnMf2sjwegbuhIjEV.jpg",
        "genre_ids": [
          878
        ],
        "id": 9482,
        "original_language": "en",
        "original_title": "Judge Dredd",
        "overview": "In a dystopian future, Dredd, the most famous judge (a cop with instant field judiciary powers) is convicted for a crime he did not commit while his murderous counterpart escapes.",
        "popularity": 20.158,
        "poster_path": "/cfSnKn8NDU3m8UxihjVcYprA0Aq.jpg",
        "release_date": "1995-06-30",
        "title": "Judge Dredd",
        "video": false,
        "vote_average": 5.765,
        "vote_count": 2135
      },
      {
        "adult": false,
        "backdrop_path": "/nEmOmbCWBXS3tHU2N49z693KDK.jpg",
        "genre_ids": [
          878,
          28,
          27
        ],
        "id": 8077,
        "original_language": "en",
        "original_title": "Alien³",
        "overview": "After escaping with Newt and Hicks from the alien planet, Ripley crash lands on Fiorina 161, a prison planet and host to a correctional facility. Unfortunately, although Newt and Hicks do not survive the crash, a more unwelcome visitor does. The prison does not allow weapons of any kind, and with aid being a long time away, the prisoners must simply survive in any way they can.",
        "popularity": 28.338,
        "poster_path": "/hlabk6APJUeihZDaSD9N6iI0f4g.jpg",
        "release_date": "1992-05-22",
        "title": "Alien³",
        "video": false,
        "vote_average": 6.4,
        "vote_count": 4945
      },
      {
        "adult": false,
        "backdrop_path": "/ikr0UILfvRerzMNoBTtJtyuWAEV.jpg",
        "genre_ids": [
          878,
          27,
          28
        ],
        "id": 8078,
        "original_language": "en",
        "original_title": "Alien Resurrection",
        "overview": "Two hundred years after Lt. Ripley died, a group of scientists clone her, hoping to breed the ultimate weapon. But the new Ripley is full of surprises … as are the new aliens. Ripley must team with a band of smugglers to keep the creatures from reaching Earth.",
        "popularity": 33.48,
        "poster_path": "/9aRDMlU5Zwpysilm0WCWzU2PCFv.jpg",
        "release_date": "1997-11-12",
        "title": "Alien Resurrection",
        "video": false,
        "vote_average": 6.1,
        "vote_count": 4270
      },
      {
        "adult": false,
        "backdrop_path": "/h6UcOYmiwliqG2a0hHqvPsA4n4C.jpg",
        "genre_ids": [
          28,
          53,
          80
        ],
        "id": 8195,
        "original_language": "en",
        "original_title": "Ronin",
        "overview": "A briefcase with undisclosed contents – sought by Irish terrorists and the Russian mob – makes its way into criminals' hands. An Irish liaison assembles a squad of mercenaries, or 'ronin', and gives them the thorny task of recovering the case.",
        "popularity": 24.279,
        "poster_path": "/AirrhRJjHwytOV0pdLu7YZ4DEyr.jpg",
        "release_date": "1998-09-25",
        "title": "Ronin",
        "video": false,
        "vote_average": 6.936,
        "vote_count": 2066
      },
      {
        "adult": false,
        "backdrop_path": "/8YNNyQiPZlF9qv5EGOUK20mnXVk.jpg",
        "genre_ids": [
          28,
          12,
          878,
          53
        ],
        "id": 262500,
        "original_language": "en",
        "original_title": "Insurgent",
        "overview": "Beatrice Prior must confront her inner demons and continue her fight against a powerful alliance which threatens to tear her society apart.",
        "popularity": 45.022,
        "poster_path": "/dP5Fb6YRfzmCQtRbHOr2kO7tJW9.jpg",
        "release_date": "2015-03-18",
        "title": "Insurgent",
        "video": false,
        "vote_average": 6.363,
        "vote_count": 9392
      }
    ],
    "total_pages": 84,
    "total_results": 1668
  }
}"""