package com.keetr.snac.core.network.tv.fake

val EpisodeDetailsResponse = """{
  "air_date": "2011-12-11",
  "crew": [
    {
      "job": "Writer",
      "department": "Writing",
      "credit_id": "550d757b9251414695005a04",
      "adult": false,
      "gender": 1,
      "id": 1214523,
      "known_for_department": "Acting",
      "name": "Konnie Huq",
      "original_name": "Konnie Huq",
      "popularity": 1.336,
      "profile_path": "/s2NNZ8oVEBHfsxyJPiJNQZZyIvp.jpg"
    },
    {
      "job": "Director",
      "department": "Directing",
      "credit_id": "550d7536c3a3684883005ba0",
      "adult": false,
      "gender": 2,
      "id": 1216417,
      "known_for_department": "Directing",
      "name": "Euros Lyn",
      "original_name": "Euros Lyn",
      "popularity": 3.069,
      "profile_path": "/7EUPE3Umh3wsL0LkOMqmEqFPgDH.jpg"
    },
    {
      "job": "Producer",
      "department": "Production",
      "credit_id": "58f22e28c3a3682e6600a6c7",
      "adult": false,
      "gender": 0,
      "id": 70503,
      "known_for_department": "Production",
      "name": "Barney Reisz",
      "original_name": "Barney Reisz",
      "popularity": 3.668,
      "profile_path": null
    },
    {
      "job": "Director of Photography",
      "department": "Camera",
      "credit_id": "5cf7754a92514153b7b8a463",
      "adult": false,
      "gender": 0,
      "id": 41534,
      "known_for_department": "Camera",
      "name": "Damian Bromley",
      "original_name": "Damian Bromley",
      "popularity": 1.206,
      "profile_path": "/ddc8AUhcIqwbQjJnMTgVPDkEKxE.jpg"
    },
    {
      "job": "Line Producer",
      "department": "Production",
      "credit_id": "5cf782650e0a265933ca269b",
      "adult": false,
      "gender": 0,
      "id": 1402091,
      "known_for_department": "Production",
      "name": "Emma Pike",
      "original_name": "Emma Pike",
      "popularity": 1.62,
      "profile_path": null
    },
    {
      "job": "Production Design",
      "department": "Art",
      "credit_id": "5cf78314c3a3684eb9208d31",
      "adult": false,
      "gender": 2,
      "id": 1120224,
      "known_for_department": "Visual Effects",
      "name": "Daniel May",
      "original_name": "Daniel May",
      "popularity": 0.6,
      "profile_path": null
    },
    {
      "job": "Original Music Composer",
      "department": "Sound",
      "credit_id": "5cf79073c3a36833de21c31a",
      "adult": false,
      "gender": 2,
      "id": 63357,
      "known_for_department": "Sound",
      "name": "Stephen McKeon",
      "original_name": "Stephen McKeon",
      "popularity": 1.313,
      "profile_path": null
    },
    {
      "job": "Editor",
      "department": "Editing",
      "credit_id": "5cf79080c3a36818d61e8219",
      "adult": false,
      "gender": 0,
      "id": 57643,
      "known_for_department": "Editing",
      "name": "Jamie Pearson",
      "original_name": "Jamie Pearson",
      "popularity": 0.84,
      "profile_path": null
    },
    {
      "job": "Writer",
      "department": "Writing",
      "credit_id": "5cf7aab70e0a2665bdccb334",
      "adult": false,
      "gender": 2,
      "id": 211845,
      "known_for_department": "Writing",
      "name": "Charlie Brooker",
      "original_name": "Charlie Brooker",
      "popularity": 2.608,
      "profile_path": "/dmdLd5I4cnpCZzoITm26NOwu6Rn.jpg"
    }
  ],
  "episode_number": 2,
  "guest_stars": [
    {
      "character": "Bingham 'Bing' Madsen",
      "credit_id": "550d75be925141469c0059b5",
      "order": 11,
      "adult": false,
      "gender": 2,
      "id": 206919,
      "known_for_department": "Acting",
      "name": "Daniel Kaluuya",
      "original_name": "Daniel Kaluuya",
      "popularity": 28.043,
      "profile_path": "/a07Tqzgp0IrW9YkcOQiuKavP4tm.jpg"
    },
    {
      "character": "Abi Khan",
      "credit_id": "550d75d292514133c3003851",
      "order": 13,
      "adult": false,
      "gender": 1,
      "id": 567269,
      "known_for_department": "Acting",
      "name": "Jessica Brown Findlay",
      "original_name": "Jessica Brown Findlay",
      "popularity": 20.904,
      "profile_path": "/xrvuOGSkS0ufxQohk2DhUV57QmE.jpg"
    },
    {
      "character": "Judge Hope",
      "credit_id": "550d7602c3a3684874006359",
      "order": 15,
      "adult": false,
      "gender": 2,
      "id": 4757,
      "known_for_department": "Acting",
      "name": "Rupert Everett",
      "original_name": "Rupert Everett",
      "popularity": 18.695,
      "profile_path": "/7t77pzlJnSLSXTzQLUey3YAzaxQ.jpg"
    },
    {
      "character": "Dustin",
      "credit_id": "550d75ecc3a3684872005fdf",
      "order": 503,
      "adult": false,
      "gender": 2,
      "id": 311811,
      "known_for_department": "Acting",
      "name": "Paul Popplewell",
      "original_name": "Paul Popplewell",
      "popularity": 2.321,
      "profile_path": "/2rhOBTlnbG9gJVqq0EJnz2hHfCQ.jpg"
    },
    {
      "character": "Judge Charity",
      "credit_id": "550d762792514146910058ac",
      "order": 504,
      "adult": false,
      "gender": 1,
      "id": 1836,
      "known_for_department": "Acting",
      "name": "Julia Davis",
      "original_name": "Julia Davis",
      "popularity": 5.232,
      "profile_path": "/wsUNCSKoNQTgSdlr9FIeIR6hRAd.jpg"
    },
    {
      "character": "Judge Wraith",
      "credit_id": "550d7646c3a3684872005fe9",
      "order": 505,
      "adult": false,
      "gender": 2,
      "id": 1636813,
      "known_for_department": "Acting",
      "name": "Ashley Thomas",
      "original_name": "Ashley Thomas",
      "popularity": 3.079,
      "profile_path": "/rdNgke4IL7x3mORHKE8HtbOAF8F.jpg"
    },
    {
      "character": "Glee",
      "credit_id": "550d765d925141469c0059e2",
      "order": 506,
      "adult": false,
      "gender": 1,
      "id": 570323,
      "known_for_department": "Acting",
      "name": "Kerrie Hayes",
      "original_name": "Kerrie Hayes",
      "popularity": 3.273,
      "profile_path": "/gLgs1LWxMmC8T11qoR0tOWP2tgj.jpg"
    },
    {
      "character": "Selma Telse",
      "credit_id": "59abca7d92514107af028217",
      "order": 568,
      "adult": false,
      "gender": 1,
      "id": 1408809,
      "known_for_department": "Acting",
      "name": "Hannah John-Kamen",
      "original_name": "Hannah John-Kamen",
      "popularity": 19.772,
      "profile_path": "/V8P9EVelewGVXbuyEylqrzF6iG.jpg"
    },
    {
      "character": "Swift",
      "credit_id": "5a2ce14a0e0a264cbe144bf0",
      "order": 569,
      "adult": false,
      "gender": 1,
      "id": 234930,
      "known_for_department": "Acting",
      "name": "Isabella Laughland",
      "original_name": "Isabella Laughland",
      "popularity": 4.469,
      "profile_path": "/5Od1m1YlSQvsggZhFwzRRFmskPX.jpg"
    },
    {
      "character": "Oliver",
      "credit_id": "5a2ce157925141032c14ab28",
      "order": 570,
      "adult": false,
      "gender": 0,
      "id": 204807,
      "known_for_department": "Acting",
      "name": "David Fynn",
      "original_name": "David Fynn",
      "popularity": 2.196,
      "profile_path": "/oYdxEyUugBx2V25gs52DVvlx7th.jpg"
    },
    {
      "character": "Kai",
      "credit_id": "5a2ce160925141033013f377",
      "order": 571,
      "adult": false,
      "gender": 2,
      "id": 1512263,
      "known_for_department": "Acting",
      "name": "Colin Michael Carmichael",
      "original_name": "Colin Michael Carmichael",
      "popularity": 3.254,
      "profile_path": "/lsJmDAmJq9mShYJ93NeyYaBVsYu.jpg"
    },
    {
      "character": "Hammond",
      "credit_id": "5a2ce16c0e0a264ccd14c44e",
      "order": 572,
      "adult": false,
      "gender": 2,
      "id": 1762541,
      "known_for_department": "Acting",
      "name": "Eugene O'Hare",
      "original_name": "Eugene O'Hare",
      "popularity": 1.012,
      "profile_path": null
    },
    {
      "character": "Anna",
      "credit_id": "5a2ce1740e0a264cd0149172",
      "order": 573,
      "adult": false,
      "gender": 1,
      "id": 1625157,
      "known_for_department": "Acting",
      "name": "Jaimi Barbakoff",
      "original_name": "Jaimi Barbakoff",
      "popularity": 1.313,
      "profile_path": "/9mqV7AAxtM5spI0Q0vKU3j91HY3.jpg"
    }
  ],
  "name": "Fifteen Million Merits",
  "overview": "After failing to impress the judges on a singing competition show, a woman must either perform degrading acts or return to a slave-like existence.",
  "id": 877836,
  "production_code": "",
  "runtime": 62,
  "season_number": 1,
  "still_path": "/c62HKSbeTRkatK223O3m58CmmPd.jpg",
  "vote_average": 7.646,
  "vote_count": 287
}"""